### ISSUE TITLE
Add Spanish (Argentina) (es_AR) Support  

### ISSUE THREAD

**Issue by VictiniFan360** [q4os/q4os-i18n#36]
#### EN:   
Hello, Q4OS Team,  

We, the Argentine people, kindly ask for official support for Spanish (Argentina) (`es_AR`) in your distribution. This is not just about adding a locale; it's about ensuring inclusivity and proper representation for our Rioplatense Spanish variant, which has unique linguistic characteristics distinct from other Spanish dialects.  

Additionally, Trinity Desktop Environment (TDE) has recently changed the default locale for Spanish to `es_AR` when Argentina is selected as the country. Without explicit support for this locale, users who choose Argentina during the installation may experience inconsistencies or functionality issues.  

We believe it is essential to respect and acknowledge the cultural and linguistic diversity within Spanish-speaking countries. Providing support for `es_AR` ensures a smoother and more inclusive experience for Argentine users.  

Thank you for considering our request. We deserve to see our language properly represented in Q4OS, a distribution many of us enjoy.  

#### ES-AR:  
Hola, equipo de Q4OS,  

Nosotros, los argentinos, pedimos amablemente soporte oficial para Español (Argentina) (`es_AR`) en su distribución. No se trata solo de agregar un locale; se trata de garantizar inclusión y representación adecuada para nuestro español rioplatense, que tiene características lingüísticas únicas y distintas de otros dialectos del español.  

Además, el entorno Trinity Desktop (TDE) recientemente cambió el locale predeterminado de español a `es_AR` cuando se selecciona Argentina como país. Sin soporte explícito para este locale, los usuarios que elijan Argentina durante la instalación podrían experimentar inconsistencias o problemas de funcionalidad.  

Creemos que es fundamental respetar y reconocer la diversidad cultural y lingüística dentro de los países hispanohablantes. Proveer soporte para `es_AR` asegura una experiencia más fluida e inclusiva para los usuarios argentinos.  

Gracias por considerar nuestro pedido. Merecemos ver nuestra lengua adecuadamente representada en Q4OS, una distribución que muchos de nosotros disfrutamos.

**Comment by q4osteam** [comment]
We have added es_AR locale to the project. Thanks for heads up.
